# Generated by Django 4.2.3 on 2023-07-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasklists', '0003_alter_task_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='tasklists/screenshots/'),
        ),
    ]
